# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
  # apt_packages:
  #   - cmake
  #   - autotools-dev
  #   - automake
  #   - gfortran
  #   - bison
  #   - libgsl-dev
  #   - libfftw3-dev
  #   - libcfitsio-dev
  #   - swig
  # jobs:
  #   # Installing numpy before anything else to avoid CCL error
  #   post_create_environment:
  #     - pip install numpy

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py
   fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  # Install only the dependencies needed to build the documentation without
  # installing the full package to avoid having to compile CCL & CAMB.
  install:
    - method: pip
      path: doc/requirements.txt
