name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - mpi4py
  - pip
  - numpy
  - wheel
  - namaster
  # tjpcov is only available at the moment through PyPi
  - pip:
    # Installing TJPcov in two steps to avoid making NaMaster installation to
    # fail due to (https://github.com/LSSTDESC/NaMaster/issues/138)
    - tjpcov[full]
