name: tjpcov
channels: 
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - wheel
  - black
  - flake8
  - pytest
  - pytest-rerunfailures
  - coveralls
  - numpy
  - scipy
  - pyyaml
  - pyccl>=3.2
  - sacc>=0.12
  - namaster>2
  - camb
  - Jinja2
  - healpy
  - h5py
  - openmpi
  - mpi4py

