name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # Installing TJPcov in two steps to avoid making NaMaster installation to
  # fail due to (https://github.com/LSSTDESC/NaMaster/issues/138)
  - tjpcov
  - tjpcov[full]
  - mpi4py
