name: tjpcov
channels: 
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - wheel
  - black
  - flake8
  - pytest
  - pytest-rerunfailures
  - coveralls
  - numpy
    # - scipy
  - scipy<1.12 # <1.12 to avoid bug in CCL<3.1 (not in pypy) with simpson integration
  - pyyaml
  - pyccl>=3.0.0
  - sacc>=0.12
  - namaster>2
  - camb
  - Jinja2
  - healpy
  - h5py
  - openmpi
  - mpi4py

