name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
dependencies:
  - python>=3.8
  - cmake
  - gsl
  - fftw
  - pip
  - namaster
  - openmpi-mpicc
  - numpy # Install numpy early so namaster builds first try.
  - pip:
    - .[full]
