name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - cmake
  - gsl
  - fftw
  - pip
  - namaster
  - openmpi-mpicc
  - numpy # Install numpy first here before pip to make sure pymaster installs
  - pip:
    - .[full]
