name: tjpcov
channels: 
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - wheel
  - black
  - flake8
  - pytest
  - pytest-rerunfailures
  - coveralls
  - numpy
  - scipy
  - pyyaml
  - pyccl>=3.0.0
  - sacc>=0.12
  - namaster
  - camb
  - Jinja2
  - healpy
  - h5py
  - openmpi
  - mpi4py

