name: tjpcov
channels: 
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - wheel
  - black
  - flake8
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - coveralls
  - numpy
  - scipy
  - pyyaml
  - pyccl >= 2.5.0, < 2.8.0
  - sacc>=0.8
  - namaster
  - camb
  - Jinja2
  - healpy
  - h5py
  - openmpi
  - mpi4py
  
