name: tjpcov
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - healpy
  - jinja2
  - h5py
  - mpi4py
  - namaster
  - pytest
  - pytest-rerunfailures
  - pip
  - pip:
    - camb