name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Install pypa/build
      run: |
        python -m pip install build --user

    - name: Build wheel and source tarball
      run: |
        python -m build

    # For now publish to test pypi until sure everything is ok
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy
